import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";
import { processPDF } from "@/lib/ai/ingestion";
import dotenv from "dotenv";

dotenv.config({ override: true });

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY || '',
    baseURL: process.env.OPENAI_BASE_URL || undefined,
});

export async function POST(req: NextRequest) {
    try {
        if (!process.env.OPENAI_API_KEY) {
            console.error("CRITICAL: OPENAI_API_KEY is missing from environment variables.");
            throw new Error("Missing OpenAI API Key. Please check your .env file.");
        }
        console.log("Prediction request received");

        const formData = await req.formData().catch(err => {
            console.error("Failed to parse formData:", err);
            throw new Error(`FormData Parse Failed: ${err.message}`);
        });
        const file = formData.get("file") as File | null;


        if (!file) {
            console.log("No file provided in request");
            return NextResponse.json({ error: "No file provided" }, { status: 400 });
        }

        console.time("predict-api-total");
        console.log(`Processing file: ${file.name} (${file.type})`);
        let rawText = "";

        if (file.type === "application/pdf" || file.name.endsWith(".pdf")) {
            console.log("PDF detected, starting extraction...");
            const chunks = await processPDF(file);
            console.log(`PDF processed, extracted ${chunks.length} chunks`);
            // Optimize context window for speed vs accuracy balance
            rawText = chunks.map((c: any) => c.pageContent).join("\n").slice(0, 9000);
        } else {
            console.log("Non-PDF file detected, reading as text...");
            const bytes = await file.arrayBuffer();
            const buffer = Buffer.from(bytes);
            rawText = buffer.toString('utf-8').slice(0, 4000);
        }

        console.log(`Extracted ${rawText.length} characters of text.`);

        const prompt = `
  Analyze this academic material and extract key signals with high technical depth. 
  
  RETURN ONLY A JSON OBJECT:
  {
    "predictions": [
      { "question": "High-probability exam question topic", "confidence": 0.95, "reason": "Why this is likely to appear" }
    ],
    "technicalMatrix": [
      { "concept": "Core concept name", "difficulty": "Low|Medium|High", "priority": "Must Study", "prob": 90 }
    ],
    "distillation": "# [Topic] Strategic Briefing\\n\\n## 1. Prime Theory\\n[Detailed explanation of the main concept]\\n\\n## 2. Structural Breakdown\\n* concept - description\\n* concept - description\\n\\n## 3. Why This Matters\\n[Contextualize for exams]\\n\\n## 4. Technical Nuance & Warning\\n[Explain common student pitfalls/misunderstandings in this topic]"
  }

  STRICT INSTRUCTION: Be verbose and pedagogical in the 'distillation'. Use multiple paragraphs and bold key terms. DO NOT provide a single-sentence summary.
  STRICT: NO "Transformers" or "Hackathon" generic data unless in the text.
  CONTEXT: "${rawText}"
`;

        console.log("Calling AI...");
        console.time("openai-call");
        const modelName = process.env.OPENAI_BASE_URL?.includes("openrouter.ai")
            ? "openai/gpt-4o-mini"
            : "gpt-4o-mini";

        const response = await openai.chat.completions.create({
            model: modelName,
            messages: [{ role: "user", content: prompt }],
            response_format: { type: "json_object" },
            max_tokens: 3000,
            temperature: 0.3,
        }).catch(err => {
            console.error("OpenAI call failed:", err);
            if (err.status === 401 || err.status === 403) {
                throw new Error(`AI Authentication Failed (Status ${err.status}).`);
            }
            throw new Error(`OpenAI API failed: ${err.message}`);
        });
        console.timeEnd("openai-call");


        const rawContent = response.choices[0].message.content;
        if (!rawContent) throw new Error("No content generated by OpenAI");

        const finalized = JSON.parse(rawContent);
        console.timeEnd("predict-api-total");

        return NextResponse.json({
            ...finalized,
            // Provide empty fallbacks for fields removed but expected by UI
            mermaidChart: "",
            vaultBlocks: [],
            dependencyMatrix: [],
            gapAnalysis: []
        });
    } catch (error: any) {
        console.error("--- PREDICTION ENGINE ERROR ---");
        console.error("Message:", error.message);
        console.error("Stack:", error.stack);
        return NextResponse.json({
            error: error.message || "Prediction Engine Failed",
            details: error.stack || "No additional details",
        }, { status: 500 });
    }

}
